services:
  api:
    build: .
    container_name: adaptive_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo
      - redis
      - chromadb
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8001:8001"
    volumes:
      - chroma_data:/chroma

volumes:
  mongo_data:
  chroma_data:
